### PR TITLE
add support gtag 'set'

### PR DESCRIPTION
**Pull request by vincent-scw**
In order to support set UserId, we can add `gtag('set', {'user_id': this.userId});` to enable a User Id view.

### CODE REVIEW

**Comment by peterecofit** [comment]
This would be great!

**Comment by joaoeduardo** [comment]
When this will be merged?

**Comment by vincent-scw** [comment]
Hey @codediodeio , do you have some time to take a look at the PRs?

**Comment by codediodeio** [comment]
Merged and released in v1.0.4, thank you @vincent-scw

**Pull request merged**
